Поскольку есть риск,
что файл по указанному пути не существует,
вся эта операция находится внутри блока try,
чтобы обработать возможное исключение FileNotFoundException.